service: golang


custom:
  scripts:
    commands:
      make-public: gcloud functions add-iam-policy-binding ${self:service}-dev-bitbucket-webhook-handler --member="allUsers" --role="roles/cloudfunctions.invoker" --project=${self:provider.project} --region=${self:provider.region} | xargs echo
    hooks:
      'after:deploy:deploy': npx sls make-public --function=bitbucket-webhook-handler

provider:
  region: us-central1
  name: google
  runtime: go116
  project: ${env:GOOGLE_PROJECT_NAME}
  credentials: ${env:GOOGLE_CREDENTIALS_JSON_FILE}

frameworkVersion: '3'

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - .gitignore
    - .git/**

functions:
  bitbucket-webhook-handler:
    handler: WebhookHandler
    events:
      - http: path
    environment:
      BITBUCKET_USERNAME:
        ${env:BITBUCKET_USERNAME}
      BITBUCKET_REPO_OWNER:
        ${env:BITBUCKET_REPO_OWNER}
      BITBUCKET_REPO_SLUG:
        ${env:BITBUCKET_REPO_SLUG}
    secrets:
      BITBUCKET_PASSWORD:
        secret: BITBUCKET_PASSWORD
        version: latest
