service: golang

provider:
  name: google
  runtime: go116
  project: ${env:GOOGLE_PROJECT_NAME}
  credentials: ${env:GOOGLE_CREDENTIALS_JSON_FILE}

frameworkVersion: '3'

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - .gitignore
    - .git/**

functions:
  bitbucket-webhook-handler:
    handler: WebhookHandler
    events:
      - http: path
    secrets:
      BITBUCKET_PASSWORD:
        secret: BITBUCKET_PASSWORD
        version: latest
